# Generated by Django 2.1.3 on 2018-12-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='sellerEmail',
            field=models.CharField(default='example@mail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='userId',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.CharField(default='example@mail.com', max_length=200),
        ),
    ]
