# Generated by Django 2.1.3 on 2018-12-05 03:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='item',
        ),
    ]
