# Generated by Django 2.1.3 on 2018-12-05 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20181205_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Profile'),
        ),
    ]
