# Generated by Django 2.1.3 on 2018-12-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20181227_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
        migrations.AddField(
            model_name='item',
            name='level',
            field=models.CharField(choices=[('初中', '初中'), ('高中', '高中')], default='高中', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='stream',
            field=models.CharField(choices=[('all', '全部'), ('理科', '理科'), ('文商', '文商科'), ('商', '商科')], max_length=4),
        ),
    ]
