# Generated by Django 2.1.3 on 2018-12-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20181227_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='level',
            field=models.CharField(choices=[('全部', '全部'), ('初中', '初中'), ('高中', '高中')], default='高中', max_length=2),
        ),
    ]
